### ISSUE TITLE
yaml support

### ISSUE THREAD

**Issue by avidseeker** [bullets-vim/bullets.vim#154]
# 1
```yaml
- date: 09-17
  todo: <enter>
```
Result:
```yaml
- date: 09-17
  todo:
-
```
Expected:
```yaml
- date: 09-17
  todo:
    -
```

# 2
```yaml
- date: 09-17
  todo:
- <tab>
```
Result:
```yaml
- date: 09-17
  todo:
  *
```
Expected:
```yaml
- date: 09-17
  todo:
    -
```
